LOBBY_STATE = "lobby_state"
GAME_STATE = "game_state"

INVALID_SESSION = "invalid_session"
SESSION_VALIDATED = "session_validated"
DUPLICATE_PLAYER = "duplicate_player"
WELCOME = "welcome"
GAME_STARTED = "game_started"
START_GAME = "start_game"

VALIDATE_PARTIAL = "validate_partial"
PARTIAL_VALIDATION = "partial_validation"
MOVE = "move"
CHAT = "chat"

CONNECT = "connect"
PLAYER_JOINED_GAME = "player_joined_game"
PLAYER_QUIT = "player_quit"
PLAYER_RECONNECTED = "player_reconnected"
PLAYER_DISCONNECTED = "player_disconnected"

ERROR = "error"
DEBUG = "debug"
UPDATE_NUM_PLAYERS = "update_num_players"
KICK_PLAYER = "kick_player"
KICKED_FROM_LOBBY = "kicked_from_lobby"
LEAVE_LOBBY = "leave_lobby"
LEAVE_GAME = "leave_game"
SERVER_HEARTBEAT = "server_heartbeat"
