PUBLIC_SERVER_HOST = "chinesecheckers.webhop.me"  # Networked testing
# PUBLIC_SERVER_HOST = "127.0.0.1"    # Local testing
LISTEN_HOST = "0.0.0.0"
SERVER_PORT = 5555
PROTOCOL_VERSION = 2
HEARTBEAT_INTERVAL = 10
SERVER_TIMEOUT = 30
